"""Ledgerloop core domain.

The vocabulary, value objects, entities, and ports that everything else is
built on. This package has no dependencies outside the standard library and
performs no I/O - adapters depend on it, never the other way round.
"""

from ledgerloop.core.enums import (
    ActionKind,
    ApprovalDecision,
    ApprovalState,
    Currency,
    Effort,
    FailureClass,
    IdempotencyState,
    LedgerEventType,
    PolicyEffect,
    RiskTier,
    RunState,
    StepOutcome,
    StopReason,
)
from ledgerloop.core.errors import (
    ApprovalRequired,
    BudgetExhaustedError,
    CompensationError,
    ConcurrencyError,
    ConfigurationError,
    DeadlineExceededError,
    IdempotencyConflictError,
    IndeterminateError,
    LedgerIntegrityError,
    LedgerloopError,
    PolicyViolationError,
    ProviderError,
    RunNotFoundError,
    StateTransitionError,
    ToolExecutionError,
)
from ledgerloop.core.ids import (
    ActionId,
    ApprovalId,
    CorrelationId,
    EntryId,
    Identifier,
    IdempotencyKey,
    RunId,
    StepId,
    TenantId,
)
from ledgerloop.core.models import (
    GENESIS_HASH,
    Action,
    ActionReceipt,
    ApprovalRequest,
    IdempotencyRecord,
    LedgerEntry,
    PolicyDecision,
    Run,
    RunBudget,
    RunSpec,
    Step,
    TokenSpend,
)
from ledgerloop.core.money import Money
from ledgerloop.core.ports import (
    ActionDispatcher,
    ApprovalGateway,
    Clock,
    EventPublisher,
    IdempotencyStore,
    LedgerStore,
    PolicyEngine,
    RunStore,
    StepStore,
    UnitOfWork,
)

__all__ = [
    "GENESIS_HASH",
    # enums
    "ActionKind",
    "ApprovalDecision",
    "ApprovalState",
    "Currency",
    "Effort",
    "FailureClass",
    "IdempotencyState",
    "LedgerEventType",
    "PolicyEffect",
    "RiskTier",
    "RunState",
    "StepOutcome",
    "StopReason",
    # identifiers
    "ActionId",
    "ApprovalId",
    "CorrelationId",
    "EntryId",
    "Identifier",
    "IdempotencyKey",
    "RunId",
    "StepId",
    "TenantId",
    # value objects
    "Money",
    "TokenSpend",
    "RunBudget",
    # entities
    "Action",
    "ActionReceipt",
    "ApprovalRequest",
    "IdempotencyRecord",
    "LedgerEntry",
    "PolicyDecision",
    "Run",
    "RunSpec",
    "Step",
    # errors
    "ApprovalRequired",
    "BudgetExhaustedError",
    "CompensationError",
    "ConcurrencyError",
    "ConfigurationError",
    "DeadlineExceededError",
    "IdempotencyConflictError",
    "IndeterminateError",
    "LedgerIntegrityError",
    "LedgerloopError",
    "PolicyViolationError",
    "ProviderError",
    "RunNotFoundError",
    "StateTransitionError",
    "ToolExecutionError",
    # ports
    "ActionDispatcher",
    "ApprovalGateway",
    "Clock",
    "EventPublisher",
    "IdempotencyStore",
    "LedgerStore",
    "PolicyEngine",
    "RunStore",
    "StepStore",
    "UnitOfWork",
]
